### ISSUE TITLE
nodegit segfault when cloning repo

### ISSUE THREAD

**Issue by bazza** [Automattic/dserve#157]
The current version of nodegit required by dserve, 0.23.1 segfaults when trying to clone a remote repo.  This is reproducible on Debian Stable (10) using this example code from nodegit

```var Git = require("nodegit");

var console = require("console");
console.log( "Here, before clone");
// Clone a given repository into the `./tmp` folder.
Git.Clone("https://github.com/nodegit/nodegit", "./tmp")
  // Look up this known commit.
  .then(function(repo) {
    // Use a known commit sha from this repository.
	console.log( "Here, in commit lookup");
    return repo.getCommit("59b20b8d5c6ff8d09518454d4dd8b7b30f095ab5");
  })
  // Look up a specific file within that commit.
  .then(function(commit) {
	console.log( "Here, in clone");
    return commit.getEntry("README.md");
  })
  // Get the blob contents from the file.
  .then(function(entry) {
    // Patch the blob to contain a reference to the entry.
    return entry.getBlob().then(function(blob) {
      blob.entry = entry;
      return blob;
    });
  })
  // Display information about the blob.
  .then(function(blob) {
    // Show the path, sha, and filesize in bytes.
    console.log(blob.entry.path() + blob.entry.sha() + blob.rawsize() + "b");

    // Show a spacer.
    console.log(Array(72).join("=") + "\n\n");

    // Show the entire file.
    console.log(String(blob));
  })
  .catch(function(err) { console.log(err); });
```

Because of this segfault, bootstrapping dserve is impossible (it will never be able to close the wp-calypso repo.  It looks like the latest version of nodegit fixes the segfault, but there are other errors when trying to use it - it seems like there might be some API changes.

```
dserve-304-37 yarn[41746]: {"name":"dserve","hostname":"dserve-304-37.dca.wordpress.com","pid":41779,"level":50,"err":{"message":"Callback is required and must be a Function.","name":"Error","stack":"Error: Callback is required and must be a Function.\n    at /home/dserve/src/node_modules/nodegit-promise/lib/node-extensions.js:24:20\n    at tryCallTwo (/home/dserve/src/node_modules/nodegit-promise/lib/core.js:45:5)\n    at doResolve (/home/dserve/src/node_modules/nodegit-promise/lib/core.js:173:13)\n    at new Promise (/home/dserve/src/node_modules/nodegit-promise/lib/core.js:65:3)\n    at Repository.getReferences (/home/dserve/src/node_modules/nodegit-promise/lib/node-extensions.js:19:12)\n    at /home/dserve/src/build/api.js:221:52\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/dserve/src/build/api.js:5:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"repository":"Automattic/wp-calypso","msg":"Error creating branchName --> commitSha map","time":"2020-05-02T22:34:13.388Z","src":{"file":"/home/dserve/src/src/api.ts","line":326},"v":0}
```

Updating nodegit is probably required for #156 so trying to fix this segfault probably isn't worth it, but wanted to document it here for completeness.

**Comment by griffbrad** [comment]
Fixed by #159
